version: '3.3'

services:
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_PID: Express
    ports:
      - 1433:1433
    volumes:
      - mssql-volume:/var/opt/mssql
    networks:
      - mssql-networks


volumes:
  mssql-volume:

networks:
  mssql-networks:
    driver: bridge